#--------------------------
# Load Database
#--------------------------

#--------------------------
# Insert Film
#--------------------------

INSERT INTO spaceplus.film 
 (title, rating, release_date, director, description, duration, price, language, thumbnail)
VALUES
 ('Interestelar', 4.9, '07-11-2014', 'Christopher Nolan', 'Um grupo de exploradores faz uso de um buraco de minhoca recém-descoberto para superar as limitações de viagem espacial humana e conquistar as vastas distâncias envolvidas em uma viagem interestelar.', '2h 49m', 48.59, 'Inglês', 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg'),
 ('Ilha do Medo', 4.4, '13-02-2010', 'Martin Scorsese', 'Em 1954, os agentes federais dos Estados Unidos, Edward Teddy Daniels e seu novo parceiro Chuck Aule viajam para o Hospital Ashecliffe para os criminosos insanos em Shutter Island, no Boston Harbor. Eles estão investigando o desaparecimento da paciente Rachel Solando, encarcerada por afogar seus três filhos. Sua única pista é uma nota enigmática encontrada escondida no quarto de Solando: A lei de 4; quem é 67?. Os dois homens chegam pouco antes de uma enorme tempestade, impedindo seu retorno ao continente por alguns dias.', '1h 56m', 67.69, 'Inglês', 'https://upload.wikimedia.org/wikipedia/pt/2/2d/Shutter_island_poster_promocional.png'),
 ('Os Infiltrados', 3.9, '06-08-2006', 'Martin Scorsese', 'Quando era criança, Colin Sullivan (Damon) tinha sido apresentado a uma organização criminosa irlandesa-americana de Frank Costello (Nicholson), no bairro Irlandês de South Boston. Ao longo dos anos, Costello prepara o ainda garoto Sullivan para entrar infiltrado na polícia do estado de Massachusetts, até que Sullivan é aceito na Unidade de Investigações Especiais, que incide sobre o crime organizado. Antes de se formar na academia de polícia, Billy Costigan (DiCaprio) é recrutado pelo capitão Queenan (Sheen) e o sargento Dignam (Wahlberg) para ir disfarçado, devido seus laços familiares com o crime organizado o que faz dele um agente infiltrado perfeito e de confiança. Ele sai da academia e passa um tempo na prisão devido a uma falsa acusação de assalto, um teste, para aumentar a sua confiança e credibilidade aos olhos de Queenan e Dignam, que precisam dessa prova para aceitar Costigan na Polícia, que possui notas altas a nível de um astronauta de que a um mero polícial.', '2h 31m', 42.77, 'Inglês', 'https://upload.wikimedia.org/wikipedia/pt/thumb/b/b8/TheDepartedposter.jpg/250px-TheDepartedposter.jpg'),
 ('O Lobo De Wall Street', 4.5, '25-12-2013', 'Martin Scorsese', 'Em 1987, Jordan Belfort (Leonardo DiCaprio) torna-se um corretor de ações em uma empresa estabelecida em Wall Street. Seu chefe, Mark Hanna (Matthew McConaughey) recomenda-lhe que adote um estilo de vida cheio de drogas e prostitutas, a fim de ter sucesso. Ele passa no Exame Série 7 e ganha sua licença de corretor, e em seu primeiro dia como corretor, a empresa quebra após a segunda-feira negra.', '3h 00m', 64.81, 'Inglês', 'https://upload.wikimedia.org/wikipedia/pt/thumb/8/8d/The_Wolf_of_Wall_Street.jpg/250px-The_Wolf_of_Wall_Street.jpg'),
 ('Oppenheimer', 4.6, '20-07-2023', 'Christopher Nolan', 'Em 1926, o estudante de doutorado J. Robert Oppenheimer, de 22 anos, estuda com o físico experimental Patrick Blackett no Laboratório Cavendish, em Cambridge. Após muito tempo longe de seu lar e sofrendo de ansiedade em decorrência do trabalho no laboratório, Oppenheimer deixa para o exigente Blackett uma maçã envenenada, porém, a recupera das mãos do cientista visitante Niels Bohr, que fica impressionado o suficiente com seu intelecto para recomendar que ele estude física teórica na Alemanha, onde Oppenheimer completa seus estudos do PhD. Mais tarde, conhece o físico teórico Werner Heisenberg em uma conferência na Suíça.', '3h 00m', 96.99, 'Inglês', 'https://upload.wikimedia.org/wikipedia/pt/thumb/5/5b/Oppenheimer_poster.jpg/250px-Oppenheimer_poster.jpg'),
 ('Taxi Driver', 4.1, '08-02-1976', 'Martin Scorsese', 'Travis Bickle é um jovem de 26 anos frustrado e alienado do meio-oeste dos Estados Unidos, que alega ter sido recentemente dispensado do Corpo de Fuzileiros Navais. Ele sofre de insônia e consequentemente arranja um emprego como taxista na cidade de Nova Iorque, oferecendo-se para trabalhar no turno da madrugada. Travis passa o seu tempo livre assistindo a filmes pornográficos em cinemas imundos, dirigindo sem rumo pela periferia de Manhattan. Também observa Nova York de seu táxi e irrompe com violência contra o que julga ser a escória que contamina a cidade.', '1h 00m', 60.87, 'Inglês', 'https://upload.wikimedia.org/wikipedia/pt/3/33/Taxi_Driver_%281976_film_poster%29.jpg');

