/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-04-22 08:22:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.browser;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import spaceplus.model.dto.Film;

public final class browser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("spaceplus.model.dto.Film");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\" />\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("  <title>Browser</title>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"browser/style.css\">\n");
      out.write("  <script defer src=\"https://use.fontawesome.com/releases/v5.1.0/js/all.js\" integrity=\"sha384-3LK/3kTpDE/Pkp8gTNp2gR/2gOiwQ6QaO7Td0zV76UFJVhqLl4Vl3KL1We6q6wR9\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("  <script src=\"main.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <div class=\"wrapper\">\n");
      out.write("\n");
      out.write("    <!-- HEADER -->\n");
      out.write("    <header>\n");
      out.write("      <div class=\"netflixLogo\">\n");
      out.write("        <a class=\"logo_space\" href=\"\">Space+</a>\n");
      out.write("      </div>      \n");
      out.write("      <nav class=\"main-nav\">                \n");
      out.write("        <select id=\"selector\">\n");
      out.write("          <option>Título</option>\n");
      out.write("          <option>Diretor</option>\n");
      out.write("          <option>Descrição</option>\n");
      out.write("          <option>Linguagem</option>\n");
      out.write("        </select>\n");
      out.write("        <input id=\"search\" class=\"search_input\" type=\"text\" placeholder=\"Pesquisar...\">\n");
      out.write("        <button id=\"commit\" type=\"button\">Pesquisar</button>\n");
      out.write("      </nav>\n");
      out.write("      <div class=\"create_buttom\" onclick=\"create()\"></div>\n");
      out.write("    </header>\n");
      out.write("    <!-- END OF HEADER -->\n");
      out.write("    \n");
      out.write("    ");
 List<Film> films = (List<Film>)request.getAttribute("films"); 
      out.write("\n");
      out.write("    ");
 boolean isSearch = (boolean)request.getAttribute("isSearch"); 
      out.write("\n");
      out.write("    ");
 if (!films.isEmpty()) { 
      out.write("\n");
      out.write("\n");
      out.write("    ");
 if (isSearch) { 
      out.write("\n");
      out.write("    <section class=\"main-container\" >\n");
      out.write("      <div class=\"location\" id=\"home\">\n");
      out.write("          <h1 id=\"home\">Baseado na sua pesquisa</h1>\n");
      out.write("          <div class=\"box\">\n");
      out.write("          ");
 for (int i = 0; i < films.size(); i++) { 
      out.write(" \n");
      out.write("          <a href= ");
      out.print( new String("/spaceplus/view?id=" + films.get(i % films.size()).id()) );
      out.write(" > <img ");
      out.print( new String("src=\"" + films.get(i % films.size()).thumbnail() + "\"") );
      out.write(" alt=\"\"> </a>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    <!-- MAIN CONTAINER -->\n");
      out.write("    <section class=\"main-container\" >\n");
      out.write("      <div class=\"location\" id=\"home\">\n");
      out.write("          <h1 id=\"home\">Popular na SpaceX</h1>\n");
      out.write("          <div class=\"box\">\n");
      out.write("          ");
 for (int i = 0; i < 12; i++) { 
      out.write(" \n");
      out.write("          <a href= ");
      out.print( new String("/spaceplus/view?id=" + films.get(i % films.size()).id()) );
      out.write(" > <img ");
      out.print( new String("src=\"" + films.get(i % films.size()).thumbnail() + "\"") );
      out.write(" alt=\"\"> </a>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("\n");
      out.write("      <h1 id=\"myList\">Em Alta</h1>\n");
      out.write("      <div class=\"box\">\n");
      out.write("          ");
 for (int i = 0; i < 6; i++) { 
      out.write(" \n");
      out.write("          <a href= ");
      out.print( new String("/spaceplus/view?id=" + films.get(i % films.size()).id()) );
      out.write(" > <img ");
      out.print( new String("src=\"" + films.get(i % films.size()).thumbnail() + "\"") );
      out.write(" alt=\"\"> </a>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <h1 id=\"tvShows\">Para Você</h1>\n");
      out.write("      <div class=\"box\">\n");
      out.write("          ");
 for (int i = 0; i < 12; i++) { 
      out.write(" \n");
      out.write("          <a href= ");
      out.print( new String("/spaceplus/view?id=" + films.get(i % films.size()).id()) );
      out.write(" > <img ");
      out.print( new String("src=\"" + films.get(i % films.size()).thumbnail() + "\"") );
      out.write(" alt=\"\"> </a>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("\n");
      out.write("      <h1 id=\"movies\">Filmes de Ação</h1>\n");
      out.write("      <div class=\"box\">\n");
      out.write("          ");
 for (int i = 0; i < 6; i++) { 
      out.write(" \n");
      out.write("          <a href= ");
      out.print( new String("/spaceplus/view?id=" + films.get(i % films.size()).id()) );
      out.write(" > <img ");
      out.print( new String("src=\"" + films.get(i % films.size()).thumbnail() + "\"") );
      out.write(" alt=\"\"> </a>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <h1 id=\"originals\">Original da Space+</h1>\n");
      out.write("      <div class=\"box\">\n");
      out.write("          ");
 for (int i = 0; i < 6; i++) { 
      out.write(" \n");
      out.write("          <a href= ");
      out.print( new String("/spaceplus/view?id=" + films.get(i % films.size()).id()) );
      out.write(" > <img ");
      out.print( new String("src=\"" + films.get(i % films.size()).thumbnail() + "\"") );
      out.write(" alt=\"\"> </a>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("     \n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("      ");
 } else {
      out.write("\n");
      out.write("    <section class=\"main-container\" >\n");
      out.write("      <div class=\"location\" id=\"home\">\n");
      out.write("          <h1 id=\"home\">Desculpa... Não encontramos nada!</h1>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    <!-- END OF MAIN CONTAINER -->\n");
      out.write("\n");
      out.write("    <!-- FOOTER -->\n");
      out.write("    <footer>\n");
      out.write("      <p>Space+ &copy 2024</p>\n");
      out.write("    </footer>\n");
      out.write("  </div>\n");
      out.write("  <script src=\"browser/script.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
