/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-04-18 22:06:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <title>Space+</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"star.css\">\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("<div class=\"background-main\">\n");
      out.write("      <div class=\"main\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <header class=\"header_main\">\n");
      out.write("      <div class=\"header_container\">\n");
      out.write("        <div class=\"area_logo\">\n");
      out.write("          <a href=\"\">Space+</a>\n");
      out.write("        </div>\n");
      out.write("        <nav class=\"nav_area\">\n");
      out.write("          <div class=\"body_nav\">\n");
      out.write("            <ul class=\"list_nav\">\n");
      out.write("              <li><a href=\"#compromisso\">Nosso Compromisso</a></li>\n");
      out.write("              <li><a href=\"#privacidade\">Privacidade & SeguranÃ§a</a></li>\n");
      out.write("              <li><a href=\"#acessibilidade\">Acessibilidade</a></li>\n");
      out.write("              <li><a href=\"#customizaÃ§Ã£o\">Melhor CustomizaÃ§Ã£o</a></li>\n");
      out.write("              <li><a href=\"#comeÃ§ar\">Como ComeÃ§ar</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </nav>\n");
      out.write("      </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- home page first display -->\n");
      out.write("    <section class=\"main_display\">\n");
      out.write("      <!-- main title container -->\n");
      out.write("      <div class=\"title_container\">\n");
      out.write("        <h1 class=\"title_text\">Space+</h1>\n");
      out.write("      </div>\n");
      out.write("      <!-- line divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("      <!-- title sub text -->\n");
      out.write("      <div class=\"sub-title_text_container\">\n");
      out.write("        <p class=\"sub-title_text\">Space+ Ã© o seu oÃ¡sis cinematogrÃ¡fico, onde vocÃª encontra todas as opÃ§Ãµes necessÃ¡rias para desfrutar de uma excelente experiáº½ncia de streaming de filmes. Nossa variedade e conveniÃªncia estÃ£o aqui para ajudar vocÃª e gerenciar e enriquecer suas sessÃµes de entretenimento.</p>\n");
      out.write("      </div>\n");
      out.write("      <!-- main button container -->\n");
      out.write("      <div class=\"button_container\">\n");
      out.write("        <!-- first button -->\n");
      out.write("        <a id=\"saiba_mais\" href=\"#compromisso\" class=\"link\">\n");
      out.write("          <span class=\"button_text\">Saiba mais</span>\n");
      out.write("        </a>\n");
      out.write("        <!-- second button -->\n");
      out.write("        <a id=\"login\" href=\"/login\" class=\"link\">\n");
      out.write("          <span class=\"button_text\">Login</span>\n");
      out.write("        </a>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- slider -->\n");
      out.write("    <section>\n");
      out.write("    <!-- slider image -->\n");
      out.write("      <div class=\"slider\">\n");
      out.write("        <div class=\"slide-track\">\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("          <div class=\"slide\"><img src=\"image.jpg\" alt=\"\" /></div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("    <!-- compromisso -->\n");
      out.write("    <section id=\"compromisso\" class=\"section_display\">\n");
      out.write("      <!-- compromisso title -->\n");
      out.write("      <div class=\"title_container_default\">\n");
      out.write("        <h1 class=\"title_text_default\">Amplie a diversÃ£o para todos</h1>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("      <!-- compromisso sub-title -->\n");
      out.write("      <div class=\"sub-title_text_container_default\">\n");
      out.write("        <p class=\"sub-title_text_default\">No Space+, acreditamos que todos os amantes de filmes, de todas as idades e origens, merecem as ferramentas e habilidade que os conduzem a descobrir e desfrutar de uma ampla seleÃ§Ã£o de filmes para todos os gostos.</p>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("    </section>\n");
      out.write("    <!-- privacidade -->\n");
      out.write("    <section id=\"privacidade\" class=\"section_display\">\n");
      out.write("      <!-- compromisso title -->\n");
      out.write("      <div class=\"title_container_default\">\n");
      out.write("        <h1 class=\"title_text_default\">Privacidade & SeguranÃ§a</h1>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("      <!-- compromisso sub-title -->\n");
      out.write("      <div class=\"sub-title_text_container_default\">\n");
      out.write("        <p class=\"sub-title_text_default\">Space+ estÃ¡ empenhado em construir um sistema que ajude os clientes a proteger sua privacidade. Oferecemos os mais altos nÃ­veis de seguranÃ§a para garantir que suas informaÃ§Ãµes e preferÃªncias estejam sempre protegidas contra ameaÃ§as em constante evoluÃ§Ã£o.</p>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("    </section>\n");
      out.write("    <!-- acessibilidade -->\n");
      out.write("    <section id=\"acessibilidade\" class=\"section_display\">\n");
      out.write("      <!-- compromisso title -->\n");
      out.write("      <div class=\"title_container_default\">\n");
      out.write("        <h1 class=\"title_text_default\">Acessibilidade para todo mundo</h1>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("      <!-- compromisso sub-title -->\n");
      out.write("      <div class=\"sub-title_text_container_default\">\n");
      out.write("        <p class=\"sub-title_text_default\">Quando todos os cinÃ©filos podem desfrutar plenamente da experiÃªncia de assistir a filmes da forma mais adequada, todos se beneficiam. Por isso, desenvolvemos o Space+ com foco em criar um sistema altamente acessÃ­vel, para ajudar todos os clientes a explorar e aproveitar ao mÃ¡ximo seu potencial cinematogrÃ¡fico.</p>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("    </section>\n");
      out.write("    <!-- customizaÃ§Ã£o -->\n");
      out.write("    <section id=\"customizaÃ§Ã£o\" class=\"section_display\">\n");
      out.write("      <!-- compromisso title -->\n");
      out.write("      <div class=\"title_container_default\">\n");
      out.write("        <h1 class=\"title_text_default\">PersonalizaÃ§Ã£o de primeira qualidade!</h1>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("      <!-- compromisso sub-title -->\n");
      out.write("      <div class=\"sub-title_text_container_default\">\n");
      out.write("        <p class=\"sub-title_text_default\">Seja vocÃª fÃ£ de clÃ¡ssicos, apaixonado por filmes de aÃ§Ã£o ou entusiasta de comÃ©dias romÃ¢nticas, o Space+ oferece as melhores ferramentas e recursos para personalizar e fornecer um catÃ¡logo de filmes que seja a melhor opÃ§Ã£o para vocÃª e suas preferÃªncias.</p>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("    </section>\n");
      out.write("    <!-- comeÃ§ar -->\n");
      out.write("    <section id=\"comeÃ§ar\" class=\"section_display\">\n");
      out.write("      <!-- compromisso title -->\n");
      out.write("      <div class=\"title_container_default\">\n");
      out.write("        <h1 class=\"title_text_default\">Como comeÃ§ar a usar os serviÃ§os do Space+</h1>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("      <!-- compromisso sub-title -->\n");
      out.write("      <div class=\"sub-title_text_container_default\">\n");
      out.write("        <p class=\"sub-title_text_default\">Estamos aqui para ajudar vocÃª em cada etapa dessa jornada, desde a escolha dos filmes atÃ© a experiÃªncia de aluguel e muito mais. Oferecemos treinamento e suporte completo sempre que vocÃª precisar, seja para responder a uma pergunta especÃ­fica, resolver qualquer problema ou descobrir mais sobre tudo o que o Space+ pode proporcionar. Estamos Ã  sua disposiÃ§Ã£o!</p>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("    </section>\n");
      out.write("    <style src=\"script.js\"></style>\n");
      out.write("    <footer class=\"footer\">\n");
      out.write("        <p class=\"footer_text\">Copyright Â© 2024 - Space+</p>\n");
      out.write("    </footer>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
