/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-04-22 09:38:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import spaceplus.model.dto.Film;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("spaceplus.model.dto.Film");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <title>Space+</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"home/style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"home/star.css\">\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("<div class=\"background-main\">\n");
      out.write("      <div class=\"main\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <header class=\"header_main\">\n");
      out.write("      <div class=\"header_container\">\n");
      out.write("        <div class=\"area_logo\">\n");
      out.write("          <a href=\"\">Space+</a>\n");
      out.write("        </div>\n");
      out.write("        <nav class=\"nav_area\">\n");
      out.write("          <div class=\"body_nav\">\n");
      out.write("            <ul class=\"list_nav\">\n");
      out.write("              <li><a href=\"#compromisso\">Nosso Compromisso</a></li>\n");
      out.write("              <li><a href=\"#privacidade\">Privacidade & Segurança</a></li>\n");
      out.write("              <li><a href=\"#acessibilidade\">Acessibilidade</a></li>\n");
      out.write("              <li><a href=\"#customização\">Melhor Customização</a></li>\n");
      out.write("              <li><a href=\"#começar\">Como Começar</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </nav>\n");
      out.write("      </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- home page first display -->\n");
      out.write("    <section class=\"main_display\">\n");
      out.write("      <!-- main title container -->\n");
      out.write("      <div class=\"title_container\">\n");
      out.write("        <h1 class=\"title_text\">Space+</h1>\n");
      out.write("      </div>\n");
      out.write("      <!-- line divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("      <!-- title sub text -->\n");
      out.write("      <div class=\"sub-title_text_container\">\n");
      out.write("        <p class=\"sub-title_text\">Space+ é o seu oásis cinematográfico, onde você encontra todas as opções necessárias para desfrutar de uma excelente experiẽncia de streaming de filmes. Nossa variedade e conveniência estão aqui para ajudar você e gerenciar e enriquecer suas sessões de entretenimento.</p>\n");
      out.write("      </div>\n");
      out.write("      <!-- main button container -->\n");
      out.write("      <div class=\"button_container\">\n");
      out.write("        <!-- first button -->\n");
      out.write("        <a id=\"saiba_mais\" href=\"#compromisso\" class=\"link\">\n");
      out.write("          <span class=\"button_text\">Saiba mais</span>\n");
      out.write("        </a>\n");
      out.write("        <!-- second button -->\n");
      out.write("        <a id=\"login\" href=\"/spaceplus/login\" class=\"link\">\n");
      out.write("          <span class=\"button_text\">Login</span>\n");
      out.write("        </a>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- slider -->\n");
      out.write("    <section>\n");
      out.write("    <!-- slider image -->\n");
      out.write("      <div class=\"slider_container\">\n");
      out.write("        <div class=\"slide-track\">\n");
      out.write("          ");
 List<Film> films = (List<Film>)request.getAttribute("films"); 
      out.write("\n");
      out.write("          ");
 for (int i = 0; i < 28; i++) { 
      out.write(" \n");
      out.write("          <div class=\"slide\"><img ");
      out.print( new String("src=\"" + films.get(i % films.size()).thumbnail() + "\"") );
      out.write(" alt=\"\" /></div>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("    <!-- compromisso -->\n");
      out.write("    <section id=\"compromisso\" class=\"section_display\">\n");
      out.write("      <!-- compromisso title -->\n");
      out.write("      <div class=\"title_container_default\">\n");
      out.write("        <h1 class=\"title_text_default\">Amplie a diversão para todos</h1>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("      <!-- compromisso sub-title -->\n");
      out.write("      <div class=\"sub-title_text_container_default\">\n");
      out.write("        <p class=\"sub-title_text_default\">No Space+, acreditamos que todos os amantes de filmes, de todas as idades e origens, merecem as ferramentas e habilidade que os conduzem a descobrir e desfrutar de uma ampla seleção de filmes para todos os gostos.</p>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("    </section>\n");
      out.write("    <!-- privacidade -->\n");
      out.write("    <section id=\"privacidade\" class=\"section_display\">\n");
      out.write("      <!-- compromisso title -->\n");
      out.write("      <div class=\"title_container_default\">\n");
      out.write("        <h1 class=\"title_text_default\">Privacidade & Segurança</h1>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("      <!-- compromisso sub-title -->\n");
      out.write("      <div class=\"sub-title_text_container_default\">\n");
      out.write("        <p class=\"sub-title_text_default\">Space+ está empenhado em construir um sistema que ajude os clientes a proteger sua privacidade. Oferecemos os mais altos níveis de segurança para garantir que suas informações e preferências estejam sempre protegidas contra ameaças em constante evolução.</p>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("    </section>\n");
      out.write("    <!-- acessibilidade -->\n");
      out.write("    <section id=\"acessibilidade\" class=\"section_display\">\n");
      out.write("      <!-- compromisso title -->\n");
      out.write("      <div class=\"title_container_default\">\n");
      out.write("        <h1 class=\"title_text_default\">Acessibilidade para todo mundo</h1>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("      <!-- compromisso sub-title -->\n");
      out.write("      <div class=\"sub-title_text_container_default\">\n");
      out.write("        <p class=\"sub-title_text_default\">Quando todos os cinéfilos podem desfrutar plenamente da experiência de assistir a filmes da forma mais adequada, todos se beneficiam. Por isso, desenvolvemos o Space+ com foco em criar um sistema altamente acessível, para ajudar todos os clientes a explorar e aproveitar ao máximo seu potencial cinematográfico.</p>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("    </section>\n");
      out.write("    <!-- customização -->\n");
      out.write("    <section id=\"customização\" class=\"section_display\">\n");
      out.write("      <!-- compromisso title -->\n");
      out.write("      <div class=\"title_container_default\">\n");
      out.write("        <h1 class=\"title_text_default\">Personalização de primeira qualidade!</h1>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("      <!-- compromisso sub-title -->\n");
      out.write("      <div class=\"sub-title_text_container_default\">\n");
      out.write("        <p class=\"sub-title_text_default\">Seja você fã de clássicos, apaixonado por filmes de ação ou entusiasta de comédias românticas, o Space+ oferece as melhores ferramentas e recursos para personalizar e fornecer um catálogo de filmes que seja a melhor opção para você e suas preferências.</p>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("    </section>\n");
      out.write("    <!-- começar -->\n");
      out.write("    <section id=\"começar\" class=\"section_display\">\n");
      out.write("      <!-- compromisso title -->\n");
      out.write("      <div class=\"title_container_default\">\n");
      out.write("        <h1 class=\"title_text_default\">Como começar a usar os serviços do Space+</h1>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("      <!-- compromisso sub-title -->\n");
      out.write("      <div class=\"sub-title_text_container_default\">\n");
      out.write("        <p class=\"sub-title_text_default\">Estamos aqui para ajudar você em cada etapa dessa jornada, desde a escolha dos filmes até a experiência de aluguel e muito mais. Oferecemos treinamento e suporte completo sempre que você precisar, seja para responder a uma pergunta específica, resolver qualquer problema ou descobrir mais sobre tudo o que o Space+ pode proporcionar. Estamos à sua disposição!</p>\n");
      out.write("      </div>\n");
      out.write("      <!-- divider -->\n");
      out.write("      <hr class=\"divider\">\n");
      out.write("    </section>\n");
      out.write("    <script src=\"home/script.js\"></script>\n");
      out.write("    <footer class=\"footer\">\n");
      out.write("        <p class=\"footer_text\">Copyright © 2024 - Space+</p>\n");
      out.write("    </footer>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
